name: CI workflow

on: push

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'yarn'
        
    - name: Install deps
      run: yarn
    
    - name: Run tests
      run: yarn test